# Generated by Django 6.0 on 2026-06-03 13:15

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(db_index=True, editable=False, max_length=50, unique=True)),
                ('status', models.CharField(choices=[('issued', 'Issued'), ('paid', 'Paid'), ('cancelled', 'Cancelled')], default='issued', max_length=20)),
                ('currency', models.CharField(default='NPR', max_length=10)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('issue_date', models.DateField(default=django.utils.timezone.localdate)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('courier_provider', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='accounts.courierprovider')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='invoice', to='orders.order')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['courier_provider', 'status'], name='billing_inv_courier_3d4dbf_idx'), models.Index(fields=['courier_provider', 'issue_date'], name='billing_inv_courier_46487b_idx'), models.Index(fields=['created_at'], name='billing_inv_created_1e16da_idx')],
            },
        ),
    ]
