# Generated by Django 6.0 on 2026-06-03 13:15

import django.db.models.deletion
import myproject.storage
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=50)),
                ('last_name', models.CharField(blank=True, max_length=50)),
                ('phone_number', models.CharField(blank=True, max_length=15)),
                ('user_type', models.CharField(choices=[('consumer', 'Consumer'), ('courier_staff', 'Courier Staff'), ('rider', 'Rider'), ('admin', 'System Admin'), ('superadmin', 'System SuperAdmin')], db_index=True, default='consumer', help_text='Type of user account', max_length=30)),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user account is active')),
                ('is_verified', models.BooleanField(default=False, help_text='Designates whether user has verified their email')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether user can access admin site')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(choices=[('home', 'Home'), ('work', 'Work'), ('other', 'Other')], default='other', help_text='Address category', max_length=50)),
                ('address_line', models.TextField(help_text='Street address, building name, floor, etc.')),
                ('landmark', models.CharField(blank=True, help_text='Nearby landmark for easier location', max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('latitude', models.DecimalField(decimal_places=6, help_text='GPS latitude for precise location', max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, help_text='GPS longitude for precise location', max_digits=9)),
                ('is_default', models.BooleanField(default=False, help_text='Mark as default address for quick access')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(help_text='User who owns this address', on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Address',
                'verbose_name_plural': 'Addresses',
                'ordering': ['-is_default', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CourierProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Legal company name', max_length=255)),
                ('logo', models.ImageField(blank=True, help_text='Optional courier company logo', null=True, storage=myproject.storage.CourierLogoStorage(), upload_to='')),
                ('company_email', models.EmailField(help_text='Official company contact email', max_length=254, unique=True)),
                ('company_phone', models.CharField(help_text='Official company contact phone', max_length=15)),
                ('address_line', models.TextField(help_text='Street address of company headquarters')),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('postal_code', models.CharField(max_length=10)),
                ('country', models.CharField(default='Nepal', help_text='Country of operation', max_length=100)),
                ('operational_status', models.CharField(choices=[('pending_documents', 'Pending Document Submission'), ('under_review', 'Under Review'), ('active', 'Active'), ('suspended', 'Suspended')], db_index=True, default='pending_documents', help_text='Current operational status based on document verification', max_length=30)),
                ('is_active', models.BooleanField(default=True, help_text='Whether company can perform operations')),
                ('max_riders', models.PositiveIntegerField(default=15, help_text='Maximum number of riders allowed (subscription tier limit)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Courier Provider',
                'verbose_name_plural': 'Courier Providers',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['operational_status'], name='accounts_co_operati_d01c23_idx')],
            },
        ),
        migrations.CreateModel(
            name='CourierStaff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('operations', 'Operations Staff')], default='operations', help_text='Staff role determining access level', max_length=20)),
                ('can_manage_invitations', models.BooleanField(default=False, help_text='Permission to add/edit/remove invitations')),
                ('can_manage_riders', models.BooleanField(default=False, help_text='Permission to manage riders')),
                ('can_manage_orders', models.BooleanField(default=True, help_text='Permission to view and manage orders')),
                ('can_manage_shippings', models.BooleanField(default=True, help_text='Permission to view and manage shippings')),
                ('can_manage_settings', models.BooleanField(default=False, help_text='Permission to modify company settings')),
                ('is_active', models.BooleanField(default=True, help_text='Whether staff member is active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(help_text='Courier company this staff belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='staff_members', to='accounts.courierprovider')),
                ('user', models.OneToOneField(help_text='User account for this staff member', on_delete=django.db.models.deletion.CASCADE, related_name='courier_staff_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Courier Staff',
                'verbose_name_plural': 'Courier Staff',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('company_pan_vat', 'Company PAN/VAT Number'), ('company_registration', 'Company Registration Certificate'), ('company_additional', 'Additional Company Document'), ('rider_driving_license', 'Driving License'), ('rider_id_proof', 'National ID/Citizenship'), ('rider_vehicle_registration', 'Vehicle Registration')], db_index=True, help_text='Type of document uploaded', max_length=50)),
                ('document_number', models.CharField(blank=True, help_text='Document identification number', max_length=100)),
                ('uploaded_file', models.FileField(help_text='Uploaded document file (PDF, JPG, PNG)', storage=myproject.storage.DocumentStorage(), upload_to='')),
                ('object_id', models.PositiveIntegerField(help_text='ID of the associated entity')),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('expired', 'Expired')], db_index=True, default='pending', help_text='Current verification status', max_length=20)),
                ('verified_at', models.DateTimeField(blank=True, help_text='Timestamp when document was verified', null=True)),
                ('rejection_reason', models.TextField(blank=True, help_text='Reason for rejection (if applicable)')),
                ('issue_date', models.DateField(blank=True, help_text='Document issue date', null=True)),
                ('expiry_date', models.DateField(blank=True, help_text='Document expiry date (if applicable)', null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content_type', models.ForeignKey(help_text='Type of entity (CourierProvider or Rider)', limit_choices_to={'model__in': ('courierprovider', 'rider')}, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('verified_by', models.ForeignKey(blank=True, help_text='System Admin who verified this document', limit_choices_to={'user_type': 'system_admin'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Document Verification',
                'verbose_name_plural': 'Document Verifications',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='ProviderInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(help_text='Email address of the invited user', max_length=254)),
                ('role', models.CharField(choices=[('rider', 'Rider'), ('admin', 'Courier Admin'), ('operations', 'Operations Staff')], default='rider', help_text='Role to be assigned to the invited user', max_length=20)),
                ('invitation_token', models.CharField(db_index=True, help_text='Unique token for invitation link', max_length=64, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('expired', 'Expired'), ('revoked', 'Revoked')], db_index=True, default='pending', help_text='Current status of invitation', max_length=20)),
                ('invited_at', models.DateTimeField(auto_now_add=True, help_text='When the invitation was sent')),
                ('expires_at', models.DateTimeField(help_text='When the invitation expires (72 hours from creation)')),
                ('accepted_at', models.DateTimeField(blank=True, help_text='When the invitation was accepted', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('courier_provider', models.ForeignKey(help_text='Courier provider sending the invitation', on_delete=django.db.models.deletion.CASCADE, related_name='rider_invitations', to='accounts.courierprovider')),
                ('invited_by', models.ForeignKey(help_text='Provider admin who sent the invitation', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_invitations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Provider Invitation',
                'verbose_name_plural': 'Provider Invitations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Rider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_birth', models.DateField(blank=True, help_text='Date of birth for age verification', null=True)),
                ('emergency_contact_name', models.CharField(blank=True, help_text='Emergency contact person name', max_length=255)),
                ('emergency_contact_phone', models.CharField(blank=True, help_text='Emergency contact phone number', max_length=15)),
                ('vehicle_type', models.CharField(choices=[('bike', 'Motorcycle/Bike'), ('scooter', 'Scooter'), ('bicycle', 'Bicycle'), ('car', 'Car'), ('van', 'Van'), ('truck', 'Small Truck')], help_text='Type of vehicle used for deliveries', max_length=20)),
                ('vehicle_number', models.CharField(help_text='Vehicle registration/plate number', max_length=50, unique=True)),
                ('vehicle_model', models.CharField(blank=True, help_text='Vehicle make and model', max_length=100)),
                ('vehicle_color', models.CharField(blank=True, help_text='Vehicle color for identification', max_length=50)),
                ('operational_status', models.CharField(choices=[('pending_documents', 'Pending Document Submission'), ('under_review', 'Under Review'), ('active', 'Active'), ('suspended', 'Suspended'), ('inactive', 'Inactive')], db_index=True, default='pending_documents', help_text='Current operational status based on document verification', max_length=30)),
                ('availability_status', models.CharField(choices=[('available', 'Available'), ('busy', 'On Delivery'), ('offline', 'Offline')], db_index=True, default='offline', help_text='Current availability for accepting orders', max_length=20)),
                ('current_latitude', models.DecimalField(blank=True, decimal_places=6, help_text='Current GPS latitude', max_digits=9, null=True)),
                ('current_longitude', models.DecimalField(blank=True, decimal_places=6, help_text='Current GPS longitude', max_digits=9, null=True)),
                ('last_location_update', models.DateTimeField(blank=True, help_text='Last time location was updated', null=True)),
                ('profile_photo', models.ImageField(blank=True, help_text='Rider profile photo', null=True, storage=myproject.storage.ProfileStorage(), upload_to='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(help_text='Courier company this rider belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='riders', to='accounts.courierprovider')),
                ('user', models.OneToOneField(help_text='User account for this rider', on_delete=django.db.models.deletion.CASCADE, related_name='rider_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Rider',
                'verbose_name_plural': 'Riders',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['email'], name='accounts_us_email_74c8d6_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['user_type'], name='accounts_us_user_ty_b6cfc8_idx'),
        ),
        migrations.AddIndex(
            model_name='address',
            index=models.Index(fields=['user', 'is_default'], name='accounts_ad_user_id_c8244c_idx'),
        ),
        migrations.AddIndex(
            model_name='courierstaff',
            index=models.Index(fields=['company', 'role'], name='accounts_co_company_34075c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='courierstaff',
            unique_together={('user', 'company')},
        ),
        migrations.AddIndex(
            model_name='documentverification',
            index=models.Index(fields=['content_type', 'object_id'], name='accounts_do_content_a00faa_idx'),
        ),
        migrations.AddIndex(
            model_name='documentverification',
            index=models.Index(fields=['status'], name='accounts_do_status_052693_idx'),
        ),
        migrations.AddIndex(
            model_name='documentverification',
            index=models.Index(fields=['document_type'], name='accounts_do_documen_c223e7_idx'),
        ),
        migrations.AddIndex(
            model_name='providerinvitation',
            index=models.Index(fields=['invitation_token', 'status'], name='accounts_pr_invitat_f1a397_idx'),
        ),
        migrations.AddIndex(
            model_name='providerinvitation',
            index=models.Index(fields=['courier_provider', 'status'], name='accounts_pr_courier_110fdb_idx'),
        ),
        migrations.AddIndex(
            model_name='providerinvitation',
            index=models.Index(fields=['email', 'status'], name='accounts_pr_email_b77661_idx'),
        ),
        migrations.AddIndex(
            model_name='rider',
            index=models.Index(fields=['company', 'operational_status'], name='accounts_ri_company_9371f9_idx'),
        ),
        migrations.AddIndex(
            model_name='rider',
            index=models.Index(fields=['availability_status'], name='accounts_ri_availab_56a8ff_idx'),
        ),
        migrations.AddIndex(
            model_name='rider',
            index=models.Index(fields=['vehicle_number'], name='accounts_ri_vehicle_1ee672_idx'),
        ),
    ]
