# Generated by Django 6.0 on 2026-04-08 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_courierprovider_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='courierstaff',
            name='can_manage_riders',
            field=models.BooleanField(default=False, help_text='Permission to manage riders'),
        ),
    ]
