# Generated by Django 6.0 on 2026-04-08 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicetypepricing',
            name='service_type',
            field=models.CharField(choices=[('standard', 'Standard Delivery'), ('express', 'Express Delivery')], max_length=20, unique=True),
        ),
    ]
