# Generated by Django 6.0 on 2026-04-08 05:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RiderOrderAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('unassigned_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_rider_assignments', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rider_assignments', to='orders.order')),
                ('rider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_assignments', to='accounts.rider')),
            ],
            options={
                'ordering': ['-assigned_at'],
            },
        ),
        migrations.CreateModel(
            name='RiderLocationUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('accuracy_meters', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('speed_kmh', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('heading_degrees', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rider_location_updates', to='orders.order')),
                ('rider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_updates', to='accounts.rider')),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_updates', to='riders.riderorderassignment')),
            ],
            options={
                'ordering': ['-recorded_at'],
            },
        ),
        migrations.AddIndex(
            model_name='riderorderassignment',
            index=models.Index(fields=['order', 'is_active'], name='riders_ride_order_i_4e1c1d_idx'),
        ),
        migrations.AddIndex(
            model_name='riderorderassignment',
            index=models.Index(fields=['rider', 'is_active'], name='riders_ride_rider_i_49e96b_idx'),
        ),
        migrations.AddConstraint(
            model_name='riderorderassignment',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('order',), name='unique_active_rider_assignment_per_order'),
        ),
        migrations.AddIndex(
            model_name='riderlocationupdate',
            index=models.Index(fields=['order', 'recorded_at'], name='riders_ride_order_i_82fb09_idx'),
        ),
        migrations.AddIndex(
            model_name='riderlocationupdate',
            index=models.Index(fields=['rider', 'recorded_at'], name='riders_ride_rider_i_099265_idx'),
        ),
        migrations.AddIndex(
            model_name='riderlocationupdate',
            index=models.Index(fields=['assignment', 'recorded_at'], name='riders_ride_assignm_d4d62d_idx'),
        ),
    ]
