# Generated by Django 6.0 on 2026-05-09 08:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_proofofdelivery'),
        ('riders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='riderorderassignment',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rider_assignments', to='orders.order', unique=True),
        ),
    ]
