# Generated by Django 6.0 on 2026-06-03 13:15

import django.core.validators
import django.db.models.deletion
import myproject.storage
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BucketStop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(help_text='City at this stop', max_length=100)),
                ('state', models.CharField(help_text='State of this stop', max_length=100)),
                ('stop_order', models.PositiveIntegerField(help_text='Sequence: 1=first stop, 2=second stop, etc.')),
            ],
            options={
                'ordering': ['bucket', 'stop_order'],
            },
        ),
        migrations.CreateModel(
            name='OrderRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_number', models.CharField(editable=False, max_length=50, unique=True)),
                ('pickup_name', models.CharField(max_length=200)),
                ('pickup_phone', models.CharField(max_length=20)),
                ('pickup_address', models.TextField()),
                ('pickup_city', models.CharField(max_length=100)),
                ('pickup_state', models.CharField(max_length=100)),
                ('pickup_latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('pickup_longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('delivery_name', models.CharField(max_length=200)),
                ('delivery_phone', models.CharField(max_length=20)),
                ('delivery_address', models.TextField()),
                ('delivery_city', models.CharField(max_length=100)),
                ('delivery_state', models.CharField(max_length=100)),
                ('delivery_latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('delivery_longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('package_type', models.CharField(choices=[('document', 'Document'), ('package', 'Package')], max_length=20)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('total_quantity', models.PositiveIntegerField(default=1, help_text='Total quantity of items inside this parcel (single number used for invoices).', validators=[django.core.validators.MinValueValidator(1)])),
                ('length', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('width', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('height', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('package_description', models.TextField(blank=True)),
                ('service_type', models.CharField(choices=[('standard', 'Standard'), ('express', 'Express')], max_length=20)),
                ('payment_method', models.CharField(choices=[('cod', 'Cash on Delivery'), ('esewa', 'eSewa'), ('sender_prepaid', 'Sender Prepaid')], default='cod', max_length=20)),
                ('estimated_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('expired', 'Expired')], default='pending', max_length=20)),
                ('rejection_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('accepted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accepted_requests', to='accounts.courierprovider')),
                ('consumer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'order_requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(db_index=True, editable=False, help_text='Unique order number used for tracking and QR code generation', max_length=50, unique=True)),
                ('order_type', models.CharField(choices=[('manual', 'Manual Order'), ('online', 'Online Order')], max_length=20)),
                ('sender_name', models.CharField(max_length=200)),
                ('sender_phone', models.CharField(max_length=20)),
                ('sender_email', models.EmailField(blank=True, max_length=254)),
                ('sender_address', models.TextField()),
                ('sender_city', models.CharField(max_length=100)),
                ('sender_state', models.CharField(max_length=100)),
                ('sender_latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('sender_longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('receiver_name', models.CharField(max_length=200)),
                ('receiver_phone', models.CharField(max_length=20)),
                ('receiver_email', models.EmailField(blank=True, max_length=254)),
                ('receiver_address', models.TextField()),
                ('receiver_city', models.CharField(max_length=100)),
                ('receiver_state', models.CharField(max_length=100)),
                ('receiver_latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('receiver_longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('package_type', models.CharField(choices=[('document', 'Document'), ('package', 'Package')], max_length=20)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('total_quantity', models.PositiveIntegerField(default=1, help_text='Total quantity of items inside this parcel (single number used for invoices).', validators=[django.core.validators.MinValueValidator(1)])),
                ('length', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('width', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('height', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('package_description', models.TextField(blank=True)),
                ('service_type', models.CharField(choices=[('standard', 'Standard'), ('express', 'Express')], max_length=20)),
                ('estimated_delivery_hours', models.IntegerField(default=48)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_method', models.CharField(choices=[('cod', 'Cash on Delivery'), ('esewa', 'eSewa'), ('sender_prepaid', 'Sender Prepaid')], max_length=20)),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='pending', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('pickup_assigned', 'Pickup Assigned'), ('heading_to_pickup', 'Heading to Pickup'), ('picked_up', 'Picked Up'), ('at_origin_hub', 'At Origin Hub'), ('in_transit', 'In Transit'), ('at_destination_hub', 'At Destination Hub'), ('delivery_assigned', 'Delivery Assigned'), ('out_for_delivery', 'Out for Delivery'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled'), ('returned', 'Returned')], default='pending', max_length=30)),
                ('cancellation_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('picked_up_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('consumer', models.ForeignKey(blank=True, help_text='Required for online orders, not needed for manual orders', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to=settings.AUTH_USER_MODEL)),
                ('courier_provider', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='accounts.courierprovider')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_orders', to=settings.AUTH_USER_MODEL)),
                ('order_request', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order', to='orders.orderrequest')),
            ],
            options={
                'db_table': 'orders',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderRequestCourierResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response_type', models.CharField(choices=[('declined', 'Declined'), ('ignored', 'Ignored')], max_length=20)),
                ('reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('courier_provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_request_responses', to='accounts.courierprovider')),
                ('order_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courier_responses', to='orders.orderrequest')),
            ],
            options={
                'db_table': 'order_request_courier_responses',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_city', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('pickup_assigned', 'Pickup Assigned'), ('heading_to_pickup', 'Heading to Pickup'), ('picked_up', 'Picked Up'), ('at_origin_hub', 'At Origin Hub'), ('in_transit', 'In Transit'), ('at_destination_hub', 'At Destination Hub'), ('delivery_assigned', 'Delivery Assigned'), ('out_for_delivery', 'Out for Delivery'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled'), ('returned', 'Returned')], max_length=30)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracking_history', to='orders.order')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProofOfDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Delivery proof photo captured by the rider.', storage=myproject.storage.ProofOfDeliveryStorage(), upload_to='', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp'])])),
                ('notes', models.TextField(blank=True, help_text='Optional notes from the rider about the delivery.')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.OneToOneField(help_text='The order this proof belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='proof_of_delivery', to='orders.order')),
                ('uploaded_by', models.ForeignKey(help_text='The rider who uploaded this proof.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_pods', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Proof of Delivery',
                'verbose_name_plural': 'Proofs of Delivery',
                'db_table': 'order_proof_of_delivery',
            },
        ),
        migrations.CreateModel(
            name='TransportBucket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bucket_number', models.CharField(db_index=True, editable=False, help_text='Unique bucket tracking code for QR scanning', max_length=50, unique=True)),
                ('origin_city', models.CharField(help_text='Starting city for this bucket route', max_length=100)),
                ('origin_state', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('courier_provider', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transport_buckets', to='accounts.courierprovider')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_buckets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BucketTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('departed_origin', 'Departed from Origin Hub'), ('arrived_transit', 'Arrived at Transit Hub'), ('departed_transit', 'Departed from Transit Hub'), ('arrived_destination', 'Arrived at Destination Hub'), ('partial_unload', 'Partial Unload at Stop')], max_length=20)),
                ('location_city', models.CharField(help_text='City where scan occurred', max_length=100)),
                ('orders_updated_count', models.IntegerField(default=0, help_text='Number of orders updated by this scan')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bucket_stop', models.ForeignKey(blank=True, help_text='Related bucket stop if applicable', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tracking_events', to='orders.bucketstop')),
                ('scanned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bucket_scans', to=settings.AUTH_USER_MODEL)),
                ('bucket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracking_history', to='orders.transportbucket')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='bucketstop',
            name='bucket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stops', to='orders.transportbucket'),
        ),
        migrations.CreateModel(
            name='BucketOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loaded_orders', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bucket_links', to='orders.order')),
                ('bucket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bucket_orders', to='orders.transportbucket')),
            ],
        ),
        migrations.AddIndex(
            model_name='orderrequest',
            index=models.Index(fields=['status', 'created_at'], name='order_reque_status_10571c_idx'),
        ),
        migrations.AddIndex(
            model_name='orderrequest',
            index=models.Index(fields=['consumer', 'status'], name='order_reque_consume_369e7a_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status', 'created_at'], name='orders_status_11db6c_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['courier_provider', 'status'], name='orders_courier_526d55_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['order_number'], name='orders_order_n_1336be_idx'),
        ),
        migrations.AddIndex(
            model_name='orderrequestcourierresponse',
            index=models.Index(fields=['courier_provider', 'response_type'], name='order_reque_courier_9c63c8_idx'),
        ),
        migrations.AddIndex(
            model_name='orderrequestcourierresponse',
            index=models.Index(fields=['order_request', 'response_type'], name='order_reque_order_r_7eafab_idx'),
        ),
        migrations.AddConstraint(
            model_name='orderrequestcourierresponse',
            constraint=models.UniqueConstraint(fields=('order_request', 'courier_provider'), name='unique_order_request_courier_response'),
        ),
        migrations.AddIndex(
            model_name='ordertracking',
            index=models.Index(fields=['order', 'created_at'], name='orders_orde_order_i_9dbc81_idx'),
        ),
        migrations.AddIndex(
            model_name='ordertracking',
            index=models.Index(fields=['location_city'], name='orders_orde_locatio_b1148f_idx'),
        ),
        migrations.AddIndex(
            model_name='transportbucket',
            index=models.Index(fields=['courier_provider', 'created_at'], name='orders_tran_courier_4061bc_idx'),
        ),
        migrations.AddIndex(
            model_name='transportbucket',
            index=models.Index(fields=['origin_city', 'origin_state', 'created_at'], name='orders_tran_origin__916b68_idx'),
        ),
        migrations.AddIndex(
            model_name='buckettracking',
            index=models.Index(fields=['bucket', 'created_at'], name='orders_buck_bucket__76de6f_idx'),
        ),
        migrations.AddIndex(
            model_name='buckettracking',
            index=models.Index(fields=['location_city', 'created_at'], name='orders_buck_locatio_5149db_idx'),
        ),
        migrations.AddIndex(
            model_name='bucketstop',
            index=models.Index(fields=['bucket', 'stop_order'], name='orders_buck_bucket__01c527_idx'),
        ),
        migrations.AddIndex(
            model_name='bucketstop',
            index=models.Index(fields=['city', 'state'], name='orders_buck_city_68c192_idx'),
        ),
        migrations.AddIndex(
            model_name='bucketorder',
            index=models.Index(fields=['bucket'], name='orders_buck_bucket__cd032a_idx'),
        ),
        migrations.AddIndex(
            model_name='bucketorder',
            index=models.Index(fields=['order'], name='orders_buck_order_i_4e1f87_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='bucketorder',
            unique_together={('bucket', 'order')},
        ),
    ]
