# Generated by Django 6.0 on 2026-04-08 08:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='total_quantity',
            field=models.PositiveIntegerField(default=1, help_text='Total quantity of items inside this parcel (single number used for invoices).', validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='orderrequest',
            name='total_quantity',
            field=models.PositiveIntegerField(default=1, help_text='Total quantity of items inside this parcel (single number used for invoices).', validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
