# Generated by Django 6.0 on 2026-04-18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_total_quantity_orderrequest_total_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderrequest',
            name='payment_method',
            field=models.CharField(
                choices=[
                    ('cod', 'Cash on Delivery'),
                    ('esewa', 'eSewa'),
                    ('sender_prepaid', 'Sender Prepaid'),
                ],
                default='cod',
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(
                choices=[
                    ('cod', 'Cash on Delivery'),
                    ('esewa', 'eSewa'),
                    ('sender_prepaid', 'Sender Prepaid'),
                ],
                max_length=20,
            ),
        ),
    ]
