# Generated by Django 6.0 on 2026-05-07 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_payment_status_failed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('pickup_assigned', 'Pickup Assigned'), ('heading_to_pickup', 'Heading to Pickup'), ('picked_up', 'Picked Up'), ('at_origin_hub', 'At Origin Hub'), ('in_transit', 'In Transit'), ('at_destination_hub', 'At Destination Hub'), ('out_for_delivery', 'Out for Delivery'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled'), ('returned', 'Returned')], default='pending', max_length=30),
        ),
        migrations.AlterField(
            model_name='ordertracking',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('pickup_assigned', 'Pickup Assigned'), ('heading_to_pickup', 'Heading to Pickup'), ('picked_up', 'Picked Up'), ('at_origin_hub', 'At Origin Hub'), ('in_transit', 'In Transit'), ('at_destination_hub', 'At Destination Hub'), ('out_for_delivery', 'Out for Delivery'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled'), ('returned', 'Returned')], max_length=30),
        ),
    ]
