# Generated by Django 6.0 on 2026-05-08 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_order_status_alter_ordertracking_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(
                choices=[
                    ('pending', 'Pending'),
                    ('confirmed', 'Confirmed'),
                    ('pickup_assigned', 'Pickup Assigned'),
                    ('heading_to_pickup', 'Heading to Pickup'),
                    ('picked_up', 'Picked Up'),
                    ('at_origin_hub', 'At Origin Hub'),
                    ('in_transit', 'In Transit'),
                    ('at_destination_hub', 'At Destination Hub'),
                    ('delivery_assigned', 'Delivery Assigned'),
                    ('out_for_delivery', 'Out for Delivery'),
                    ('delivered', 'Delivered'),
                    ('cancelled', 'Cancelled'),
                    ('returned', 'Returned'),
                ],
                default='pending',
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name='ordertracking',
            name='status',
            field=models.CharField(
                choices=[
                    ('pending', 'Pending'),
                    ('confirmed', 'Confirmed'),
                    ('pickup_assigned', 'Pickup Assigned'),
                    ('heading_to_pickup', 'Heading to Pickup'),
                    ('picked_up', 'Picked Up'),
                    ('at_origin_hub', 'At Origin Hub'),
                    ('in_transit', 'In Transit'),
                    ('at_destination_hub', 'At Destination Hub'),
                    ('delivery_assigned', 'Delivery Assigned'),
                    ('out_for_delivery', 'Out for Delivery'),
                    ('delivered', 'Delivered'),
                    ('cancelled', 'Cancelled'),
                    ('returned', 'Returned'),
                ],
                max_length=30,
            ),
        ),
    ]
