# Generated by Django 6.0 on 2026-05-08 18:03

import django.core.validators
import django.db.models.deletion
import orders.models.proof_of_delivery
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_add_delivery_assigned_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProofOfDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Delivery proof photo captured by the rider.', upload_to=orders.models.proof_of_delivery.pod_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp'])])),
                ('notes', models.TextField(blank=True, help_text='Optional notes from the rider about the delivery.')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.OneToOneField(help_text='The order this proof belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='proof_of_delivery', to='orders.order')),
                ('uploaded_by', models.ForeignKey(help_text='The rider who uploaded this proof.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_pods', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Proof of Delivery',
                'verbose_name_plural': 'Proofs of Delivery',
                'db_table': 'order_proof_of_delivery',
            },
        ),
    ]
